/**
 * Import settings section — The Events Calendar WXR importer.
 */
import { useState, useRef } from '@wordpress/element';
import {
	Button,
	Notice,
	__experimentalVStack as VStack,
} from '@wordpress/components';
import { __ } from '@wordpress/i18n';

const { nonce, importUrl } = window.blockendarSettings ?? {};

function ResultsTable( { events } ) {
	if ( ! events?.length ) return null;

	return (
		<table className="blockendar-import__results widefat striped">
			<thead>
				<tr>
					<th>{ __( 'Event', 'blockendar' ) }</th>
					<th>{ __( 'Result', 'blockendar' ) }</th>
				</tr>
			</thead>
			<tbody>
				{ events.map( ( ev, i ) => (
					<tr key={ i }>
						<td>{ ev.title }</td>
						<td>
							<span className={ `blockendar-import__badge blockendar-import__badge--${ ev.status }` }>
								{ ev.status }
							</span>
							{ ev.message && <span className="blockendar-import__msg"> { ev.message }</span> }
						</td>
					</tr>
				) ) }
			</tbody>
		</table>
	);
}

export function ImportSection() {
	const [ file, setFile ]       = useState( null );
	const [ loading, setLoading ] = useState( false );
	const [ results, setResults ] = useState( null );
	const [ error, setError ]     = useState( null );
	const fileRef                 = useRef();

	const run = async ( dryRun ) => {
		if ( ! file ) return;
		setLoading( true );
		setError( null );
		setResults( null );

		const formData = new FormData();
		formData.append( 'file', file );
		if ( dryRun ) {
			formData.append( 'dry_run', '1' );
		}

		try {
			const res = await fetch( importUrl, {
				method:  'POST',
				headers: { 'X-WP-Nonce': nonce },
				body:    formData,
			} );

			const data = await res.json();

			if ( ! res.ok ) {
				throw new Error( data?.message ?? data?.error ?? __( 'Import failed.', 'blockendar' ) );
			}

			setResults( { ...data, dryRun } );
		} catch ( e ) {
			setError( e.message );
		} finally {
			setLoading( false );
		}
	};

	const summary = results
		? `${ results.imported } ${ results.dryRun ? __( 'would be imported', 'blockendar' ) : __( 'imported', 'blockendar' ) }, ${ results.skipped } ${ __( 'skipped', 'blockendar' ) }`
		: null;

	return (
		<VStack spacing={ 5 }>
			<h2>{ __( 'Import', 'blockendar' ) }</h2>

			<VStack spacing={ 3 }>
				<h3 style={ { margin: 0 } }>{ __( 'The Events Calendar', 'blockendar' ) }</h3>
				<p style={ { margin: 0, color: '#757575' } }>
					{ __( 'Import events from a WordPress WXR export generated by The Events Calendar plugin. Go to Tools → Export on the source site and export only "Events".', 'blockendar' ) }
				</p>

				<div style={ { display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' } }>
					<Button
						variant="secondary"
						onClick={ () => fileRef.current?.click() }
					>
						{ file ? file.name : __( 'Choose XML file…', 'blockendar' ) }
					</Button>

					{ file && (
						<>
							<Button
								variant="tertiary"
								onClick={ () => run( true ) }
								isBusy={ loading }
								disabled={ loading }
							>
								{ __( 'Preview', 'blockendar' ) }
							</Button>

							<Button
								variant="primary"
								onClick={ () => run( false ) }
								isBusy={ loading }
								disabled={ loading }
							>
								{ __( 'Import Events', 'blockendar' ) }
							</Button>

							<Button
								variant="tertiary"
								isDestructive
								disabled={ loading }
								onClick={ () => {
									setFile( null );
									setResults( null );
									setError( null );
									if ( fileRef.current ) fileRef.current.value = '';
								} }
							>
								{ __( 'Clear', 'blockendar' ) }
							</Button>
						</>
					) }

					<input
						ref={ fileRef }
						type="file"
						accept=".xml,text/xml"
						style={ { display: 'none' } }
						onChange={ ( e ) => {
							const f = e.target.files?.[ 0 ] ?? null;
							setFile( f );
							setResults( null );
							setError( null );
						} }
					/>
				</div>
			</VStack>

			{ error && (
				<Notice status="error" isDismissible={ false }>
					{ error }
				</Notice>
			) }

			{ results && (
				<VStack spacing={ 3 }>
					<Notice
						status={ results.dryRun ? 'info' : 'success' }
						isDismissible={ false }
					>
						{ results.dryRun
							? __( 'Preview complete — no changes were saved. ', 'blockendar' )
							: __( 'Import complete. ', 'blockendar' )
						}
						{ summary }
						{ results.errors?.length > 0 && (
							<> — { results.errors.length } { __( 'error(s)', 'blockendar' ) }</>
						) }
					</Notice>

					{ results.errors?.length > 0 && (
						<ul style={ { margin: 0, paddingLeft: '1.5em', color: '#cc1818' } }>
							{ results.errors.map( ( e, i ) => <li key={ i }>{ e }</li> ) }
						</ul>
					) }

					<ResultsTable events={ results.events } />
				</VStack>
			) }
		</VStack>
	);
}
